default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: 123456

development:
  <<: *default
  database: blog_developement

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog
